industryOptions:
  - key: "public"
    text: "Public sector"
  - key: "private"
    text: "Private sector"
  - key: "ngo"
    text: "NGO"
  - key: "academia"
    text: "Academia"
  - key: "non-profit"
    text: "Non-profit"
  - key: "other"
    text: "Other"

languageOptions:
  - key: "python"
    text: "Python"
  - key: "r"
    text: "R" 
  - key: "javascript"
    text: "JavaScript" 
  - key: "java"
    text: "Java"
  - key: "c"
    text: "C/C++"
  - key: "other"
    text: "Other"
