# Note: These options are used in the frontend "account request" form
# and the keys must match the Django choice fields used for the `signups`
# model in the pc-id app. Before making any changes here, make sure they
# are synced with that app, otherwise requests may fail.
industryOptions:
  - key: "not_specified"
    text: "Not specified"
  - key: "public"
    text: "Public sector"
  - key: "private"
    text: "Private sector"
  - key: "ngo"
    text: "NGO"
  - key: "academia"
    text: "Academia"
  - key: "non_profit"
    text: "Non-profit"
  - key: "other"
    text: "Other"

languageOptions:
  - key: "python"
    text: "Python"
  - key: "r"
    text: "R"
  - key: "javascript"
    text: "JavaScript"
  - key: "Java"
    text: "Java"
  - key: "c"
    text: "C/C++"
  - key: "other"
    text: "Other"
