# Use STAC collection IDs to attach specific notebooks/content to a collection
# detail page. Any references to Notebook html files below require the .ipynb
# file to be included in the `etl/codefiles_urls.txt` file for processing

# Omitting headerImg will reuse and stretch the collection thumbnail

# To include a button on a tab to launch the notebook in Hub, add the following
# config to the tab item. Assumes PlanetaryComputerExamples/main.

# tabs:
#   - title: My title
#     src: notebook.html
#     launch: tutorials/notebook.ipynb
#
# or, if you need to specify a different repo or branch, the full config is:
#
# tabs:
#   - title: My title
#     src: notebook.html
#     launch:
#       - repo: http://github.com/exampleorg/myrepo
#         branch: v1
#         filePath: tutorials/notebook.ipynb

---
collections:
  3dep-seamless:
    headerImg: ./images/threedep-seamless-hero.png

  daymet-daily-pr:
    headerImg: ./images/daymet-daily-pr-hero.png
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-monthly-pr:
    headerImg: ./images/daymet-monthly-pr-hero.png
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-annual-pr:
    headerImg: ./images/daymet-annual-pr-hero.png
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-daily-hi:
    headerImg: ./images/daymet-daily-hi-hero.png
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-monthly-hi:
    headerImg: ./images/daymet-monthly-hi-hero.png
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-annual-hi:
    headerImg: ./images/daymet-annual-hi-hero.png
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-daily-na:
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-monthly-na:
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  daymet-annual-na:
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch: quickstarts/reading-zarr-data.ipynb

  terraclimate:
    headerImg: ./images/terraclimate-hero.png
    headerImg: ./images/naip-hero.jpg
    # Blocked by https://github.com/microsoft/PlanetaryComputerExamples/pull/27
    tabs:
      - title: Example Notebook
        src: terraclimate-example.html
        launch: datasets/terraclimate/terraclimate-example.ipynb

  naip:
    headerImg: ./images/naip-hero.jpg
    tabs:
      - title: Example Notebook
        src: naip-example.html
        launch: datasets/naip/naip-example.ipynb
      - title: Blob Storage Notebook
        src: naip.html
      - title: Storage Documentation
        src: naip-storage.html

  landsat-8-c2-l2:
    headerImg: ./images/landsat-hero.jpg
    tabs:
      - title: Example Notebook
        src: landsat-8-c2-l2-example.html
        launch: datasets/landsat-8-c2-l2/landsat-8-c2-l2-example.ipynb
      - title: Blob Storage Notebook
        src: landsat-8.html
      - title: Storage Documentation
        src: landsat-8-storage.html

  sentinel-2-l2a:
    headerImg: ./images/sentinel-hero.jpg
    tabs:
      - title: Example Notebook
        src: sentinel-2-l2a-example.html
        launch: datasets/sentinel-2-l2a/sentinel-2-l2a-example.ipynb
      - title: Blob Storage Notebook
        src: sentinel-2.html
      - title: Storage Documentation
        src: sentinel-2-storage.html

  aster-l1t:
    headerImg: ./images/aster-hero.jpg
    tabs:
      - title: Example Notebook
        src: aster-l1t-example.html
        launch: datasets/aster-l1t/aster-l1t-example.ipynb
      - title: Blob Storage Notebook
        src: aster.html
      - title: Storage Documentation
        src: aster-storage.html

# Configuration for "other dataset" section. This list is rendered
# in the order represented here, which is mostly alphabetical, with
# some custom prioritization.
ai4e:
  - title: GBIF
    shortTerm: GBIF occurrence
    description:
      Species occurrences shared through the Global Biodiversity Information Facility
    infoUrl: http://aka.ms/ai4edata-gbif/
    thumbnailUrl: gbif.jpg
    alt: Colorful frog on a leaf
    keywords: [Global, Biodiversity, Species, GBIF]

  - title: Daymet
    shortTerm: Daymet temperature
    description: Gridded temperature data across North America
    infoUrl: http://aka.ms/ai4edata-daymet
    thumbnailUrl: RE3CbUs.jpg
    alt: Map showing color-coded temperature data.
    keywords: ["Weather", "Daymet", "North America", "Hawaii", "Puerto Rico"]

  - title: Global Hydro Estimator
    shortTerm: global precipitation
    description: Global precipitation estimates
    infoUrl: http://aka.ms/ai4edata-ghe
    thumbnailUrl: RE4ucH7.jpg
    alt: Clouds at sunset
    keywords: [Noaa, Global, Precipitation]

  - title: GOES-16
    shortTerm: GOES-16 weather
    description: Weather imagery of the Americas
    infoUrl: http://aka.ms/ai4edata-goes16
    thumbnailUrl: RE4ucH9.jpg
    alt: Raindrops hitting water
    keywords: [GOES, Weather, Americas, Imagery]

  - title: Harmonized Global Biomass
    shortTerm: global biomass
    description: Global carbon density for 2010
    infoUrl: https://aka.ms/ai4edata-hgb
    thumbnailUrl: RWz0Yf.jpg
    alt: Shaded mossy forest
    keywords: [Global, Carbon, Biomass]

  - title: Harmonized Landsat Sentinel-2
    shortTerm: HLS
    description: 30m-resolution satellite imagery for North America
    infoUrl: http://aka.ms/ai4edata-hls
    thumbnailUrl: RE3OM3E.jpg
    alt: Map of Chesapeake Bay
    keywords: [Landsat, Sentinel, Satellite, Imagery, North America]

  - title: High Resolution Electricity Access
    shortTerm: HREA
    description: Settlement-level measures of electricity access and reliability
    infoUrl: https://aka.ms/ai4edata-hrea
    thumbnailUrl: RWAaNJ.jpg
    alt: City light grid viewed from above
    keywords: [Global, Electricity]

  - title: LILA BC
    shortTerm: LILA BC
    description: Labeled images related to wildlife conservation
    infoUrl: http://lila.science/
    thumbnailUrl: RE3BWhq.jpg
    alt: Fox pup stands on a rock.
    keywords: [LILA, Labels, Wildlife, Biodiversity]

  - title: MODIS
    shortTerm: MODIS
    description:
      Satellite imagery from the Moderate Resolution Imaging Spectroradiometer
      (MODIS)
    infoUrl: https://aka.ms/ai4edata-modis
    thumbnailUrl: RE3BTDt.jpg
    alt: View of Earth from space.
    keywords: [MODIS, Satellite, Imagery, Global]

  - title: Monitoring Trends in Burn Severity Mosaics
    shortTerm: burn severity
    description: Annual burn severity for the US
    infoUrl: https://aka.ms/ai4edata-mtbs
    thumbnailUrl: RWz0Yt.jpg
    alt: Forest fire.
    keywords: [MTBS, Burn Severity, Fires, United States]

  - title: NASADEM
    shortTerm: NASADEM
    description: Global topographic survey
    infoUrl: https://aka.ms/ai4edata-nasadem
    thumbnailUrl: RE4sQYP.jpg
    alt: Topographic map showing contour lines
    keywords: [Global, DEM]

  - title: National Land Cover Database
    shortTerm: land cover
    description: US-wide data on land cover and land cover change
    infoUrl: https://aka.ms/ai4edata-nlcd
    thumbnailUrl: RWz0Zh.jpg
    alt: Landcover map of the United States
    keywords: [Land Cover, United States]

  - title: NOAA Global Forecast System
    shortTerm: NOAA global forecast
    description: 15-day US hourly weather forecast data
    infoUrl: https://aka.ms/ai4edata-gfs
    thumbnailUrl: RE4rvnx.jpg
    alt: Earth viewed from space station with a satellite
    keywords: [Global, NOAA, Weather, Temperature, Precipitation]

  - title: NOAA GFS Warm Start Conditions
    shortTerm: NOAA warm start
    description: Six-hourly initial conditions for the NOAA Global Forecast System
    infoUrl: https://aka.ms/ai4edata-gfs-warm-start
    thumbnailUrl: RE4MHyn.jpg
    alt: High altitude view of cloud cover with moon
    keywords: [Global, NOAA, Weather, Temperature, Precipitation]

  - title: NOAA Integrated Surface Data
    shortTerm: NOAA surface
    description: Worldwide hourly weather history data
    infoUrl: https://aka.ms/ai4edata-isd
    thumbnailUrl: RE4rsOQ.jpg
    alt: High altitude view of clouds
    keywords: [Global, Noaa, Weather, Temperature, Precipitation]

  - title: Ocean Observatories Initiative CAMHD
    shortTerm: OOI
    description: High-resolution video from the floor of the Pacific Ocean
    infoUrl: https://aka.ms/ai4edata-ooi-camhd
    thumbnailUrl: RE4KiKZ.jpg
    alt: Image from ocean floor video
    keywords: [OOI, Video, Ocean, Pacific]

  - title: Sentinel-1 GRD
    shortTerm: Sentinel-1 GRD
    description: Global synthetic aperture radar (SAR) data from 2017-present
    infoUrl: https://aka.ms/ai4edata-sentinel-1
    thumbnailUrl: sentinel-1-grd.jpg
    alt: False color rendering of Sentinel-1 GRD data near Seattle, WA, USA
    keywords: [Global, Sentinel, Satellite, ESA, SAR, Radar]

  - title: UK Met Office CSSP China 20CRDS
    shortTerm: CSSP China 20CRDS
    description: Historical climate data for China, from 1851-2010
    infoUrl: https://aka.ms/ai4edata-uk-met-20crds
    thumbnailUrl: cssp-china.jpg
    alt: Sky and clouds over mountain range
    keywords: [China, Climate, Historical]

  - title: USFS Forest Inventory and Analysis
    shortTerm: forest health
    description: Trends in US forest health
    infoUrl: https://aka.ms/ai4edata-fia
    thumbnailUrl: RWz2Nt.jpg
    alt: Evergreen forest with shrubbery
    keywords: [United States, Forest, Biomass]
