# Use STAC collection IDs to attach specific notebooks/content to a collection
# detail page. Any references to Notebook html files below require the .ipynb
# file to be included in the `etl/notebook_urls.txt` file for processing
collections:
  naip:
    tabs:
      - title: Getting Started 
        src: naip.html
      - title: Using Esri Image Server
        src: naip-image-server.html
      - title: Using from blob storage
        src: naip-storage.html
      - title: Landuse classification model
        src: landcover.html
        launch: 
          title: Launch in Compute
          repo: https://github.com/TomAugspurger/landcover-demo-gtc-2021
          branch: main
          filePath: landcover.ipynb
  landsat-8-c2-l2:
    tabs:
      - title: Getting Started 
        src: landsat.html
      - title: Using from blob storage
        src: landsat-storage.html
  sentinel-2-l2a:
    tabs:
      - title: Getting Started 
        src: sentinel-2.html
      - title: Using from blob storage
        src: sentinel-2-storage.html
  aster-l1t:
    tabs:
      - title: Using from blob storage
        src: aster-storage.html

# Configuration for "other dataset" section
ai4e: 
  - title: Daymet
    description: Gridded temperature data across North America
    infoUrl: http://aka.ms/ai4edata-daymet
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE3CbUs?ver=b6c7&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Map showing color-coded temperature data.

  - title: Global Hydro Estimator
    description: Global precipitation estimates
    infoUrl: http://aka.ms/ai4edata-ghe
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4ucH7?ver=9bbe&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Clouds at sunset

  - title: LILA BC
    description: Labeled images related to wildlife conservation
    infoUrl: http://lila.science/
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE3BWhq?ver=a3ee&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Fox pup stands on a rock.

  - title: MODIS Surface Reflectance
    description: 500m-resolution global daily surface reflectance dating back to 2000
    infoUrl: https://aka.ms/ai4edata-modis
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE3BTDt?ver=3fe9&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: View of Earth from space.

  - title: Monitoring Trends in Burn Severity Mosaics
    description: Annual burn severity for the US
    infoUrl: https://aka.ms/ai4edata-mtbs
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWz0Yt?ver=28e7&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Forest fire.

  - title: NASADEM
    description: Global topographic survey
    infoUrl: https://aka.ms/ai4edata-nasadem
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4sQYP?ver=5623&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Topographic map showing contour lines

  - title: National Land Cover Database
    description: US-wide data on land cover and land cover change
    infoUrl: https://aka.ms/ai4edata-nlcd
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWz0Zh?ver=8e3e&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Landcover map of the United States

  - title: NEXRAD
    description: Radar data from 159 stations across the US
    infoUrl: https://aka.ms/ai4edata-nexrad
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE3CbUp?ver=eb55&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Map of the US showing radar data.

  - title: NOAA Global Forecast System
    description: 15-day US hourly weather forecast data
    infoUrl: https://aka.ms/ai4edata-gfs
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4rvnx?ver=7332&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Earth viewed from space station with a satellite

  - title: NOAA GFS Warm Start Conditions
    description: Six-hourly initial conditions for the NOAA Global Forecast System
    infoUrl: https://aka.ms/ai4edata-gfs-warm-start
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4MHyn?ver=a18e&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: High altitude view of cloud cover with moon

  - title: NOAA Integrated Surface Data
    description: Worldwide hourly weather history data
    infoUrl: https://aka.ms/ai4edata-isd
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4rsOQ?ver=8870&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: High altitude view of clouds

  - title: Ocean Observatories Initiative CAMHD 
    description: High-resolution video from the floor of the Pacific Ocean
    infoUrl: https://aka.ms/ai4edata-ooi-camhd
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4KiKZ?ver=edc5&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Image from ocean floor video

  - title: TerraClimate
    description: Global monthly climate data from 1958-present
    infoUrl: https://aka.ms/ai4edata-terraclimate
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWz0Zk?ver=cc7b&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Rain clouds viewed from space

  - title: USFS Forest Inventory and Analysis
    description: Trends in US forest health
    infoUrl: https://aka.ms/ai4edata-fia
    thumbnailUrl: https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWz2Nt?ver=8060&q=90&m=6&h=201&w=358&b=%23FFFFFFFF&l=f&o=t&aim=true
    alt: Evergreen forest with shrubbery