# Use STAC collection IDs to attach specific notebooks/content to a collection
# detail page. Any references to Notebook html files below require the .ipynb
# file to be included in the `etl/codefiles_urls.txt` file for processing

# To include a button on a tab to launch the notebook in Hub, add the following
# config to the tab item:

# tabs:
#   - title: My title
#     src: notebook.html
#     launch:
#       repo: https://github.com/TomAugspurger/landcover-demo-gtc-2021
#       branch: main
#       filePath: landcover.ipynb
---
collections:
  daymet-daily-na:
    headerImg: 
    tabs:
      - title: Example Notebook
        src: reading-zarr-data.html
        launch:
          repo: https://github.com/microsoft/PlanetaryComputerExamples
          branch: main
          filePath: quickstarts/reading-zarr-data.ipynb

  naip:
    headerImg: ./images/naip-hero.jpg
    tabs:
      - title: Example Notebook
        src: naip-example.html
        launch:
          repo: https://github.com/microsoft/PlanetaryComputerExamples
          branch: main
          filePath: datasets/naip/naip-example.ipynb
      - title: Blob Storage Notebook
        src: naip.html
      - title: Storage Documentation
        src: naip-storage.html
  landsat-8-c2-l2:
    headerImg: ./images/landsat-hero.jpg
    tabs:
      - title: Example Notebook
        src: landsat-8-c2-l2-example.html
        launch:
          repo: https://github.com/microsoft/PlanetaryComputerExamples
          branch: main
          filePath: datasets/landsat-8-c2-l2/landsat-8-c2-l2-example.ipynb
      - title: Blob Storage Notebook
        src: landsat-8.html
      - title: Storage Documentation
        src: landsat-8-storage.html
  sentinel-2-l2a:
    headerImg: ./images/sentinel-hero.jpg
    tabs:
      - title: Example Notebook
        src: sentinel-2-l2a-example.html
        launch:
          repo: https://github.com/microsoft/PlanetaryComputerExamples
          branch: main
          filePath: datasets/sentinel-2-l2a/sentinel-2-l2a-example.ipynb
      - title: Blob Storage Notebook
        src: sentinel-2.html
      - title: Storage Documentation
        src: sentinel-2-storage.html
  aster-l1t:
    headerImg: ./images/aster-hero.jpg
    tabs:
      - title: Example Notebook
        src: aster-l1t-example.html
        launch:
          repo: https://github.com/microsoft/PlanetaryComputerExamples
          branch: main
          filePath: datasets/aster-l1t/aster-l1t-example.ipynb
      - title: Blob Storage Notebook
        src: aster.html
      - title: Storage Documentation
        src: aster-storage.html

# Configuration for "other dataset" section. This list is rendered
# in the order represented here, which is mostly alphabetical, with
# some custom prioritization.
ai4e:
  - title: GBIF
    shortTerm: GBIF occurrence
    description: Species occurrences shared through the Global Biodiversity Information Facility
    infoUrl: http://aka.ms/ai4edata-gbif/
    thumbnailUrl: gbif.jpg
    alt: Colorful frog on a leaf
    keywords: [global, biodiversity, species, gbif]

  - title: Daymet
    shortTerm: Daymet temperature
    description: Gridded temperature data across North America
    infoUrl: http://aka.ms/ai4edata-daymet
    thumbnailUrl: RE3CbUs.jpg
    alt: Map showing color-coded temperature data.
    keywords: ["weather", "daymet", "north america", "hawaii", "puerto rico"]

  - title: Global Hydro Estimator
    shortTerm: global precipitation
    description: Global precipitation estimates
    infoUrl: http://aka.ms/ai4edata-ghe
    thumbnailUrl: RE4ucH7.jpg
    alt: Clouds at sunset
    keywords: [global, precipitation]

  - title: GOES-16
    shortTerm: GOES-16 weather
    description: Weather imagery of the Americas
    infoUrl: http://aka.ms/ai4edata-goes16
    thumbnailUrl: RE4ucH9.jpg
    alt: Raindrops hitting water

  - title: Harmonized Global Biomass
    shortTerm: global biomass
    description: Global carbon density for 2010
    infoUrl: https://aka.ms/ai4edata-hgb
    thumbnailUrl: RWz0Yf.jpg
    alt: Shaded mossy forest
    keywords: [global, carbon, biomass]

  - title: Harmonized Landsat Sentinel-2
    shortTerm: HLS
    description: 30m-resolution satellite imagery for North America
    infoUrl: http://aka.ms/ai4edata-hls
    thumbnailUrl: RE3OM3E.jpg
    alt: Map of Chesapeake Bay
    keywords: [landsat, sentinel, satellite, north america]

  - title: High Resolution Electricity Access
    shortTerm: HREA
    description: Settlement-level measures of electricity access and reliability
    infoUrl: https://aka.ms/ai4edata-hrea
    thumbnailUrl: RWAaNJ.jpg
    alt: City light grid viewed from above
    keywords: [global, electricity]

  - title: LILA BC
    shortTerm: LILA BC
    description: Labeled images related to wildlife conservation
    infoUrl: http://lila.science/
    thumbnailUrl: RE3BWhq.jpg
    alt: Fox pup stands on a rock.
    keywords: [labels, wildlife, biodiversity]

  - title: MODIS
    shortTerm: MODIS
    description: Satellite imagery from the Moderate Resolution Imaging Spectroradiometer (MODIS)
    infoUrl: https://aka.ms/ai4edata-modis
    thumbnailUrl: RE3BTDt.jpg
    alt: View of Earth from space.

  - title: Monitoring Trends in Burn Severity Mosaics
    shortTerm: burn severity
    description: Annual burn severity for the US
    infoUrl: https://aka.ms/ai4edata-mtbs
    thumbnailUrl: RWz0Yt.jpg
    alt: Forest fire.

  - title: NASADEM
    shortTerm: NASADEM
    description: Global topographic survey
    infoUrl: https://aka.ms/ai4edata-nasadem
    thumbnailUrl: RE4sQYP.jpg
    alt: Topographic map showing contour lines
    keywords: [global, dem]

  - title: National Land Cover Database
    shortTerm: land cover
    description: US-wide data on land cover and land cover change
    infoUrl: https://aka.ms/ai4edata-nlcd
    thumbnailUrl: RWz0Zh.jpg
    alt: Landcover map of the United States
    keywords: [land cover, conus]

  - title: NOAA Global Forecast System
    shortTerm: NOAA global forecast
    description: 15-day US hourly weather forecast data
    infoUrl: https://aka.ms/ai4edata-gfs
    thumbnailUrl: RE4rvnx.jpg
    alt: Earth viewed from space station with a satellite
    keywords: [global, noaa, weather, temperature, precipitation]

  - title: NOAA GFS Warm Start Conditions
    shortTerm: NOAA warm start
    description: Six-hourly initial conditions for the NOAA Global Forecast System
    infoUrl: https://aka.ms/ai4edata-gfs-warm-start
    thumbnailUrl: RE4MHyn.jpg
    alt: High altitude view of cloud cover with moon
    keywords: [global, noaa, weather, temperature, precipitation]

  - title: NOAA Integrated Surface Data
    shortTerm: NOAA surface
    description: Worldwide hourly weather history data
    infoUrl: https://aka.ms/ai4edata-isd
    thumbnailUrl: RE4rsOQ.jpg
    alt: High altitude view of clouds
    keywords: [global, noaa, weather, temperature, precipitation]

  - title: Ocean Observatories Initiative CAMHD
    shortTerm: OOI
    description: High-resolution video from the floor of the Pacific Ocean
    infoUrl: https://aka.ms/ai4edata-ooi-camhd
    thumbnailUrl: RE4KiKZ.jpg
    alt: Image from ocean floor video
    keywords: [video, ocean]

  - title: Sentinel-1 GRD
    shortTerm: Sentinel-1 GRD
    description: Global synthetic aperture radar (SAR) data from 2017-present
    infoUrl: https://aka.ms/ai4edata-sentinel-1
    thumbnailUrl: sentinel-1-grd.jpg
    alt: False color rendering of Sentinel-1 GRD data near Seattle, WA, USA
    keywords: [global, sentinel, satellite, esa]

  - title: TerraClimate
    shortTerm: global climate
    description: Global monthly climate data from 1958-present
    infoUrl: https://aka.ms/ai4edata-terraclimate
    thumbnailUrl: RWz0Zk.jpg
    alt: Rain clouds viewed from space
    keywords: [global, climate, temperature]

  - title: UK Met Office CSSP China 20CRDS
    shortTerm: CSSP China 20CRDS
    description: Historical climate data for China, from 1851-2010
    infoUrl: https://aka.ms/ai4edata-uk-met-20crds 
    thumbnailUrl: cssp-china.jpg
    alt: Sky and clouds over mountain range
    keywords: [china, climate]

  - title: USFS Forest Inventory and Analysis
    shortTerm: forest health
    description: Trends in US forest health
    infoUrl: https://aka.ms/ai4edata-fia
    thumbnailUrl: RWz2Nt.jpg
    alt: Evergreen forest with shrubbery
    keywords: [conus, forest, biomass]
