product: Planetary Computer (Preview)
name: Data Catalog
description: Explore the datasets and functionality of Microsoft's Planetary Computer
author: AI for Earth <aiforearthdatasets@microsoft.com>


# The compute API section uses a notebook for its main content
compute:
  notebookSrc: ghe.html
