name: AI Environment App CI/CD and Deploy

on:
  push:
    branches:
      - feature/chat
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - feature/chat

jobs:
  build_and_deploy_job:
    environment: production
    if:
      github.event_name == 'push' || (github.event_name == 'pull_request' &&
      github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      REACT_APP_API_ROOT: ${{ secrets.API_ROOT }}
      REACT_APP_IMAGE_API_ROOT: ${{ secrets.IMAGE_API_ROOT }}
      REACT_APP_ONEDS_TENANT_KEY: ${{ secrets.ONEDS_TENANT_KEY }}
      REACT_APP_AZMAPS_KEY: ${{ secrets.AZMAPS_KEY }}
      REACT_APP_HUB_URL: ${{ secrets.HUB_URL }}

      REACT_APP_AUTH_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
      REACT_APP_AUTH_CLIENT_ID: ff405620-c73b-45cd-a14f-3bc4acc03c2e
      REACT_APP_AUTH_BACKEND_APP_ID: f37103ff-012b-4d71-a9d9-c430c0c8771d
      REACT_APP_AI_API_ROOT: https://pct-gpt-westeurope-staging.azure-api.net/api/ai/v1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Build docs and metadata
        run: ./scripts/update
      - name: Test and lint
        run: ./scripts/test
      - name: Inject disallow crawling for robots.txt
        run: |
          echo -e "User-agent: *\nDisallow: /\n" > public/robots.txt
      - name: Build optimized bundle
        id: build-bundle
        run: ./scripts/cibuild
      - name: Build And Deploy (Test)
        id: builddeploy-test
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token:
            ${{ secrets.AZURE_STATIC_WEB_APPS_AI_DEPLOYMENT_TOKEN}}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          skip_deploy_on_missing_secrets: true
          action: "upload"
          skip_app_build: true
          app_location: "build"
          api_location: "api"
          output_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token:
            ${{ secrets.AZURE_STATIC_WEB_APPS_AI_DEPLOYMENT_TOKEN}}
          action: "close"
