name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ROOT: https://planetarycomputer-staging.microsoft.com
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Specify Browser since container image is compile with Firefox
          install-command: yarn install
          start: yarn start
          wait-on: http://localhost:3000
          wait-on-timeout: 95
          browser: chrome
